// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cckewonfqbfcvlderdur.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNja2V3b25mcWJmY3ZsZGVyZHVyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3MjYyMDgsImV4cCI6MjA2ODMwMjIwOH0.LE3_aaOg4SmB2XOmlvpt2eTG7BvISnUQUJYvLFnI6-E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});